// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMicStateData, GetMicStateResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, GetStatusData, GetStatusResponses, ListAgentsData, ListAgentsResponses, SetMicStateData, SetMicStateResponses, SetTargetData, SetTargetErrors, SetTargetResponses, UpdateSettingsData, UpdateSettingsErrors, UpdateSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Fetch current settings from daemon/settings.json
 */
export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({ url: '/settings', ...options });

/**
 * Update settings (partial or full merge)
 */
export const updateSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateSettingsData, ThrowOnError>) => (options.client ?? client).post<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError>({
    url: '/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current target and mic state
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({ url: '/status', ...options });

/**
 * Get microphone state
 */
export const getMicState = <ThrowOnError extends boolean = false>(options?: Options<GetMicStateData, ThrowOnError>) => (options?.client ?? client).get<GetMicStateResponses, unknown, ThrowOnError>({ url: '/mic', ...options });

/**
 * Set microphone state
 */
export const setMicState = <ThrowOnError extends boolean = false>(options: Options<SetMicStateData, ThrowOnError>) => (options.client ?? client).post<SetMicStateResponses, unknown, ThrowOnError>({
    url: '/mic',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List available agents from relay or workspaces
 */
export const listAgents = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsData, ThrowOnError>) => (options?.client ?? client).get<ListAgentsResponses, unknown, ThrowOnError>({ url: '/agents', ...options });

/**
 * Set the current target agent
 */
export const setTarget = <ThrowOnError extends boolean = false>(options: Options<SetTargetData, ThrowOnError>) => (options.client ?? client).post<SetTargetResponses, SetTargetErrors, ThrowOnError>({
    url: '/target',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
