// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:3030' | (string & {});
};

export type Settings = {
    start_threshold: number;
    stop_threshold: number;
    tts_word_limit: number;
    tts_enabled: boolean;
    toast_duration: number;
};

export type PartialSettings = {
    start_threshold?: number;
    stop_threshold?: number;
    tts_word_limit?: number;
    tts_enabled?: boolean;
    toast_duration?: number;
};

export type StatusResponse = {
    target: string;
    micState: 'on' | 'off';
};

export type AgentsResponse = {
    agents: Array<{
        name: string;
    } | string>;
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type GetSettingsErrors = {
    /**
     * Settings file not found
     */
    404: unknown;
};

export type GetSettingsResponses = {
    /**
     * Settings object
     */
    200: Settings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: PartialSettings;
    path?: never;
    query?: never;
    url: '/settings';
};

export type UpdateSettingsErrors = {
    /**
     * Invalid JSON
     */
    400: unknown;
    /**
     * Write error
     */
    500: unknown;
};

export type UpdateSettingsResponses = {
    /**
     * Merged settings
     */
    200: Settings;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusResponses = {
    /**
     * Status object
     */
    200: StatusResponse;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetMicStateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mic';
};

export type GetMicStateResponses = {
    /**
     * Mic state
     */
    200: {
        state: 'on' | 'off';
    };
};

export type GetMicStateResponse = GetMicStateResponses[keyof GetMicStateResponses];

export type SetMicStateData = {
    body: {
        state: 'on' | 'off';
    };
    path?: never;
    query?: never;
    url: '/mic';
};

export type SetMicStateResponses = {
    /**
     * Updated mic state
     */
    200: {
        state: 'on' | 'off';
    };
};

export type SetMicStateResponse = SetMicStateResponses[keyof SetMicStateResponses];

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: {
        source?: 'relay' | 'workspaces' | 'auto';
    };
    url: '/agents';
};

export type ListAgentsResponses = {
    /**
     * Agents list
     */
    200: AgentsResponse;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type SetTargetData = {
    body: {
        target: string;
    };
    path?: never;
    query?: never;
    url: '/target';
};

export type SetTargetErrors = {
    /**
     * Missing target
     */
    400: unknown;
};

export type SetTargetResponses = {
    /**
     * Updated target
     */
    200: {
        target: string;
    };
};

export type SetTargetResponse = SetTargetResponses[keyof SetTargetResponses];
