export type KnowledgeItemId = string & { readonly __brand: 'KnowledgeItemId' }

// NOTE: 'article' maps to legacy 'web' DB values — migration pending
export type KnowledgeItemType = 'article' | 'youtube' | 'video' | 'pdf'

export type KnowledgeItemStatus = 'queued' | 'processing' | 'done' | 'error'

export interface KnowledgeItemPreview {
  id: KnowledgeItemId
  title: string
  url: string
  type: KnowledgeItemType
  status: KnowledgeItemStatus
  /** ISO 8601 string — stored as text in SQLite */
  createdAt: string
  tags: string[]
  /** Short bullet-point summary shown on list cards */
  tldr?: string[]
  /** Full prose summary generated by LLM */
  summary?: string
  /** Which model generated the summary */
  summaryModel?: string
  /** CEO starred/saved-for-later flag */
  starred?: boolean
  rating?: number
}
